#baseurl = "https://carsonseese.com"
title = "Carson"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disableKinds = ["taxonomyTerm"]

[params]
    author = "Carson Seese"
    info = "Cybersecurity Student, Certified Button Presser and Cable Plugger"
    description = "Cybersecurity Student"
    keywords = "Developer,Profile,Security,Programming"
    avatarurl = "images/avatar.jpg"

    dateformat = "January 2, 2006"
    colorscheme = "dark"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = true
    hidecopyright = false

    rtl = false
    math = false

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/cs-5/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/carsons_5"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/carsonseese/"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "https://blog.carsonseese.com"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"
